config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/shops/list"

   get "/shops/area_osaka"
   get "/shops/area_hyogo"
   get "/shops/area_kyoto"

   get "/shops/genre_fastfood"
   get "/shops/genre_cafe"
   get "/shops/genre_manga"
   get "/shops/genre_karaoke"
   get "/shops/genre_space"

  root to: 'shops#index'
  resources :shops do
    resources :comments, only: :create
    collection do
      get 'search'
  end
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ActiveHash::Base
    include ActiveHash::Associations
    has_many :shops
    self.data = [
      { id: 1, name: '--' },
      { id: 2, name: '大阪' },
      { id: 3, name: '兵庫' },
      { id: 4, name: '京都' },
      { id: 5, name: '滋賀' },
      { id: 6, name: '和歌山' },
      { id: 7, name: '奈良' },
      { id: 8, name: '東京' },
      { id: 9, name: '神奈川' },
      { id: 10, name: '埼玉' }
    ]


    end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :shop
    belongs_to :user
end

app/models/genre.rb
class Genre < ActiveHash::Base
  include ActiveHash::Associations
  has_many :shops
    self.data = [
      { id: 1, name: '--' },
      { id: 2, name: 'ファストフード' },
      { id: 3, name: 'カフェ' },
      { id: 4, name: '漫画喫茶' },
      { id: 5, name: 'カラオケ' },
      { id: 6, name: 'コワーキングスペース' },
      { id: 7, name: 'その他' }
    ]
    end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :comments

    has_one_attached :image
    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :area

    extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :genre

    def self.search(search)
        if search != ""
          Shop.where(`text LIKE(?)`, "%#{search}%")
        else
          Shop.all
        end
     end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comments = Comment.all
    @comment = Comment.new
  end
  def create
    Comment.create(comment_params)
  end
    
      private
      def comment_params
        params.require(:comment).permit(:text).merge(user_id: current_user.id, shop_id: params[:shop_id])
      end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
    def index
        @shops = Shop.all
    end
    def new
        @shop = Shop.new
    end

    def list
      @shops = Shop.all
    end

    def area_osaka
      @shops = Shop.where(area_id: 2)
    end

    def area_hyogo
      @shops = Shop.where(area_id: 3)
    end

    def area_kyoto
      @shops = Shop.where(area_id: 4)
    end

    def genre_fastfood
      @shops = Shop.where(genre_id: 2)
    end

    def genre_cafe
      @shops = Shop.where(genre_id: 3)
    end

    def genre_manga
      @shops = Shop.where(genre_id: 4)
    end

    def genre_karaoke
      @shops = Shop.where(genre_id: 5)
    end

    def genre_space
      @shops = Shop.where(genre_id: 6)
    end

    def search
      @shops = Shop.search(params[:keyword])
    end


    def create
      @shop = Shop.create(shop_params)
      if @shop.save
        redirect_to controller: :shops, action: :index
      else
        render "new"
      end
    end

    def show
      @shop = Shop.find(params[:id])
      @comment = Comment.new
      @comments = @shop.comments.includes(:user)
    end
    
      private
      def shop_params
        params.require(:shop).permit(:name, :title, :content,:open_hour,:regular_holiday,:telephone,
                                     :address,:nearest_station,:capacity,:private_room,:wifi,:power_supply,:jusyo,
                                     :genre_id,:area_id,:image)
      end

      def move_to_index
        unless user_signed_in?
          redirect_to  '/users/sign_in'
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoinWork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header class="header">
  <%= link_to image_tag("images/スクリーンショット 2021-03-27 19.03.18.png", class:"logo"), "/" %>
    <ul class="menu-item">
    <% if user_signed_in? %>
    <div class="menu-item-link">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post" %>
      <%= link_to "口コミ投稿", shops_list_path, class: "post" %>
    </div>
  <% else %>
    <div class="menu-item-link">
      <%= link_to "ログイン", new_user_session_path, class: "post" %>
      <%= link_to "新規登録", new_user_registration_path, class: "post" %>
    </div>
  <% end %>
    </ul>
  </header>
  <%= yield %>
  <footer class="footer">
    <p class="copyright">Copyright © 2021 Inc.copyright CoinWork. rights reserved.</p>
  </footer>
  </body>
</html>

app/views/shops/area_hyogo.html.erb
<div class="services-section">
  <p class="services-list-bar">店舗一覧（兵庫）</p>
</div>
<main class="main">
<% @shops.each do |shop| %>
    <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
    <div class="list-service-cardarea">
  <div class="list-service-card">
  <div class="shop-top-name">
    <span class="shop-name"><%= shop.name %></span>
    <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
  </div>
  <div class="list-service-textarea">
     <div class="list-shop-image">
        <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
      </div>
      <div class="list-shop-expanation">
        <h6 class="list-shop-explanation"><%= shop.title %></h6>
        <div class="list-color">
          <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
          <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
          <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
          <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
        </div>
      </div>
  </div>
</div>
  <% end %>
  </div>
  <% end %>
</main>

app/views/shops/area_kyoto.html.erb
<div class="services-section">
  <p class="services-list-bar">店舗一覧（京都）</p>
</div>
<main class="main">
<% @shops.each do |shop| %>
    <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
    <div class="list-service-cardarea">
  <div class="list-service-card">
  <div class="shop-top-name">
    <span class="shop-name"><%= shop.name %></span>
    <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
  </div>
  <div class="list-service-textarea">
     <div class="list-shop-image">
        <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
      </div>
      <div class="list-shop-expanation">
        <h6 class="list-shop-explanation"><%= shop.title %></h6>
        <div class="list-color">
          <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
          <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
          <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
          <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
        </div>
      </div>
  </div>
</div>
  <% end %>
  </div>
  <% end %>
</main>

app/views/shops/area_osaka.html.erb
<div class="services-section">
  <p class="services-list-bar">店舗一覧（大阪）</p>
</div>
<main class="main">
<% @shops.each do |shop| %>
    <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
    <div class="list-service-cardarea">
  <div class="list-service-card">
  <div class="shop-top-name">
    <span class="shop-name"><%= shop.name %></span>
    <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
  </div>
  <div class="list-service-textarea">
     <div class="list-shop-image">
        <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
      </div>
      <div class="list-shop-expanation">
        <h6 class="list-shop-explanation"><%= shop.title %></h6>
        <div class="list-color">
          <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
          <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
          <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
          <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
        </div>
      </div>
  </div>
</div>
  <% end %>
  </div>
  <% end %>
</main>

app/views/shops/crate.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/shops/genre_cafe.html.erb
<div class="services-section">
  <p class="services-list-bar">ジャンル（カフェ）</p>
</div>
<main class="main">
<% @shops.each do |shop| %>
    <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
    <div class="list-service-cardarea">
  <div class="list-service-card">
  <div class="shop-top-name">
    <span class="shop-name"><%= shop.name %></span>
    <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
  </div>
  <div class="list-service-textarea">
     <div class="list-shop-image">
        <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
      </div>
      <div class="list-shop-expanation">
        <h6 class="list-shop-explanation"><%= shop.title %></h6>
        <div class="list-color">
          <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
          <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
          <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
          <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
        </div>
      </div>
  </div>
</div>
  <% end %>
  </div>
  <% end %>
</main>

app/views/shops/genre_fastfood.html.erb
<div class="services-section">
  <p class="services-list-bar">ジャンル（ファストフード）</p>
</div>
<main class="main">
<% @shops.each do |shop| %>
    <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
    <div class="list-service-cardarea">
  <div class="list-service-card">
  <div class="shop-top-name">
    <span class="shop-name"><%= shop.name %></span>
    <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
  </div>
  <div class="list-service-textarea">
     <div class="list-shop-image">
        <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
      </div>
      <div class="list-shop-expanation">
        <h6 class="list-shop-explanation"><%= shop.title %></h6>
        <div class="list-color">
          <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
          <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
          <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
          <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
        </div>
      </div>
  </div>
</div>
  <% end %>
  </div>
  <% end %>
</main>

app/views/shops/genre_karaoke.html.erb
<div class="services-section">
  <p class="services-list-bar">ジャンル（カラオケ）</p>
</div>
<main class="main">
<% @shops.each do |shop| %>
    <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
    <div class="list-service-cardarea">
  <div class="list-service-card">
  <div class="shop-top-name">
    <span class="shop-name"><%= shop.name %></span>
    <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
  </div>
  <div class="list-service-textarea">
     <div class="list-shop-image">
        <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
      </div>
      <div class="list-shop-expanation">
        <h6 class="list-shop-explanation"><%= shop.title %></h6>
        <div class="list-color">
          <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
          <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
          <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
          <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
        </div>
      </div>
  </div>
</div>
  <% end %>
  </div>
  <% end %>
</main>

app/views/shops/genre_manga.html.erb
<div class="services-section">
  <p class="services-list-bar">ジャンル（漫画喫茶）</p>
</div>
<main class="main">
<% @shops.each do |shop| %>
    <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
    <div class="list-service-cardarea">
  <div class="list-service-card">
  <div class="shop-top-name">
    <span class="shop-name"><%= shop.name %></span>
    <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
  </div>
  <div class="list-service-textarea">
     <div class="list-shop-image">
        <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
      </div>
      <div class="list-shop-expanation">
        <h6 class="list-shop-explanation"><%= shop.title %></h6>
        <div class="list-color">
          <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
          <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
          <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
          <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
        </div>
      </div>
  </div>
</div>
  <% end %>
  </div>
  <% end %>
</main>

app/views/shops/genre_space.html.erb
<div class="services-section">
  <p class="services-list-bar">ジャンル（コワーキングスペース）</p>
</div>
<main class="main">
<% @shops.each do |shop| %>
    <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
    <div class="list-service-cardarea">
  <div class="list-service-card">
  <div class="shop-top-name">
    <span class="shop-name"><%= shop.name %></span>
    <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
  </div>
  <div class="list-service-textarea">
     <div class="list-shop-image">
        <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
      </div>
      <div class="list-shop-expanation">
        <h6 class="list-shop-explanation"><%= shop.title %></h6>
        <div class="list-color">
          <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
          <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
          <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
          <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
        </div>
      </div>
  </div>
</div>
  <% end %>
  </div>
  <% end %>
</main>

app/views/shops/index.html.erb
  <body>
    <main class="main">
      <div class="first-view">
        <div class="first-view-textarea">
          <h1 class="catchcopy">関西で作業場所探すなら<br>Coin-work</h1>
          <p class="subtext"></p>
          <a href="/shops/list" class="top-service-btn">詳細を見る</a>
          <%= form_with(url: search_shops_path, local: true, method: :get, class: "search-form") do |form| %>
            <%= form.text_field :keyword, placeholder: "エリア・ジャンル", class: "index-search-input" %>
            <%= form.submit "検索", class: "search-btn" %>
          <% end %>
        </div>
      </div>
      <p class="services-section-bar">ジャンルから探す</p>
      <div class="genre-area">
        <a href="/shops/genre_fastfood"><div class="genre-card">
          <h2 class="genre-img">ファストフード</h2>
          </div>
        </a>
        <a href="/shops/genre_cafe"><div class="genre-card">
          <h2 class="genre-img1">カフェ</h2>
          </div>
        </a>
        <a href="/shops/genre_manga"><div class="genre-card">
          <h2 class="genre-img2">漫画喫茶</h2>
          </div>
        </a>
        <a href="/shops/genre_karaoke"><div class="genre-card">
          <h2 class="genre-img3">カラオケ</h2>
          </div>
        </a>
        <a href="/shops/genre_space"><div class="genre-card">
          <h2 class="genre-img4">コワーキングスペース</h2>
          </div>
        </a>
       </div>
      </div>
  
      <div class="area-kensaku">
      <a href="/shops/area_osaka" class="osaka"><h1 class="timei-osaka">大阪</h1>
        <ul class="sub-osaka">
          <li class="top-area-osaka">難波</li>
          <li class="top-area-osaka">天王寺</li>
          <li class="top-area-osaka">梅田</li>
          <li class="top-area-osaka">新大阪</li>
        </ul>
        </a>
      <a href="/shops/area_hyogo" class="osaka"><h1 class="timei-hyogo">兵庫</h1>
        <ul class="sub-osaka">
          <li class="top-area-osaka">神戸</li>
          <li class="top-area-osaka">三宮</li>
          <li class="top-area-osaka">西宮</li>
          <li class="top-area-osaka">姫路</li>
        </ul>
      </a>
      <a href="/shops/area_kyoto" class="osaka"><h1 class="timei-hyogo">京都</h1>
      <ul class="sub-osaka">
        <li class="top-area-osaka">福知山</li>
        <li class="top-area-osaka">宮津</li>
        <li class="top-area-osaka">京都</li>
        <li class="top-area-osaka">宇治</li>
      </ul>
    </a>
    </div>
      
      <p class="services-section-bar">使用シーン</p>
      <div class="service-cardarea-use">
      <div class="service-card1">
          <div class="service-textarea">
            <img src="" alt="" class="service-logo">
            <h2 class="service-description">Working</h2>
            <div class="service-btn-use"><h5>電源・wifiが完備されているため、PC作業やデスクワークなどカフェやオフィス代わりとしてご利用いただけます。出張時にも便利な拠点になります。</h5></div>
          </div>
        </div>

        <div class="service-card2">
          <div class="service-textarea">
            <img src="" alt="" class="service-logo">
            <h2 class="service-description">FreeTime</h2>
            <div class="service-btn-use"><h5>休憩したいときや、待ち時間などのくつろぎスペースとしてご利用ください。携帯やPCのちょっとした充電もしていただけます。</h5></div>
          </div>
        </div>
    </div>
    <div class="service-cardarea-use">
    <div class="service-card3">
        <div class="service-textarea">
          <img src="" alt="" class="service-logo">
          <h2 class="service-description">Meeting</h2>
          <div class="service-btn-use"><h5>打ち合わせや面談、面接場所にもご利用いただけます。会議室が満室のときや、カフェで席がとれないときには、予約してご利用ください。</h5></div>
        </div>
      </div>

      <div class="service-card4">
        <div class="service-textarea">
          <img src="" alt="" class="service-logo">
          <h2 class="service-description">MeetUp</h2>
          <div class="service-btn-use"><h5>勉強会や朝活、オフ会、交流会など、さまざまな活動の拠点としてご利用いただけます。コミュニティ形成の場としても機能します。</h5></div>
        </div>
      </div>
  </div>

  <p class="services-section-bar">その他検索</p>
  <div class="other-list">
    <ul class="other-genre"><h3>ジャンル別で探す</h3>
    <div class="category-osaka">
      <a href="/shops/genre_fastfood"><li class="area-osaka">ファストフード</li></a>
      <a href="/shops/genre_cafe"><li class="area-osaka">カフェ</li></a>
      <a href="/shops/genre_karaoke"><li class="area-osaka">カラオケ</li></a>
      <a href="/shops/genre_manga"><li class="area-osaka">漫画喫茶</li></a>
      <a href="/shops/genre_space"><li class="area-osaka">コワーキングスペース</li></a>
      <a href="/shops/list"><li class="area-osaka">一覧ページ</li></a>
    </div>
    </ul>
    <ul class="other-area"><h3>その他条件・エリアで探す</h3>
    <div class="category-timei">
      <a href="/shops/area_osaka"><li class="area-osaka">大阪</li></a>
      <a href="/shops/area_osaka"><li class="area-osaka">梅田</li></a>
      <a href="/shops/area_osaka"><li class="area-osaka">新世界</li></a>
      <a href="/shops/area_osaka"><li class="area-osaka">天王寺</li></a>
      <a href="/shops/area_osaka"><li class="area-osaka">天満</li></a>
      <a href="/shops/area_kyoto"><li class="area-osaka">京都</li></a>
      <a href="/shops/area_kyoto"><li class="area-osaka">宮津</li></a>
      <a href="/shops/area_kyoto"><li class="area-osaka">天橋立</li></a>
      <a href="/shops/area_kyoto"><li class="area-osaka">京都市内</li></a>
      <a href="/shops/area_hyogo"><li class="area-osaka">兵庫</li></a>
      <a href="/shops/area_hyogo"><li class="area-osaka">姫路</li></a>
      <a href="/shops/area_hyogo"><li class="area-osaka">淡路島</li></a>
      <a href="/shops/area_hyogo"><li class="area-osaka">神戸</li></a>
      <a href="/shops/area_hyogo"><li class="area-osaka">西宮</li></a>

      <a href="/shops/area_hyogo"><li class="area-osaka">尼崎</li></a>
      <a href="/shops/area_kyoto"><li class="area-osaka">福知山</li></a>
      <a href="/shops/area_kyoto"><li class="area-osaka">宇治</li></a>
    </div>
  </ul>
  </div>
</body>

app/views/shops/list.html.erb
<div class="services-section">
  <p class="services-list-bar">店舗一覧</p>
</div>
<main class="main">
<% @shops.each do |shop| %>
    <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
    <div class="list-service-cardarea">
  <div class="list-service-card">
  <div class="shop-top-name">
    <span class="shop-name"><%= shop.name %></span>
    <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
  </div>
  <div class="list-service-textarea">
     <div class="list-shop-image">
        <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
      </div>
      <div class="list-shop-expanation">
        <h6 class="list-shop-explanation"><%= shop.title %></h6>
        <div class="list-color">
          <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
          <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
          <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
          <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
        </div>
      </div>
  </div>
</div>
  <% end %>
  </div>
  <% end %>
</main>

app/views/shops/search.html.erb
<%= form_with(url: search_shops_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="services-section">
  <p class="services-list-bar">店舗一覧</p>
</div>

  <main class="main">
  <% @shops.each do |shop| %>
      <%= link_to shop_path(shop.id),:style=>"color: #337ABA;", method: :get do %>
      <div class="list-service-cardarea">
    <div class="list-service-card">
    <div class="shop-top-name">
      <span class="shop-name"><%= shop.name %></span>
      <span class="shop-info">【<%= shop.area.name %>】 <%= shop.nearest_station %>  /  <%= shop.genre.name %></span>
    </div>
    <div class="list-service-textarea">
       <div class="list-shop-image">
          <%= image_tag shop.image, class: "list-shop-card__img" if shop.image.attached? %>
        </div>
        <div class="list-shop-expanation">
          <h6 class="list-shop-explanation"><%= shop.title %></h6>
          <div class="list-color">
            <h5 class="shop-explanation"><span class="font_test">営業時間：</span><%= shop.open_hour %></h5>
            <h5 class="shop-explanation"><span class="font_test">休業日</span>：<%= shop.regular_holiday %></h5>
            <h5 class="shop-explanation"><span class="font_test">アクセス</span>：<%= shop.nearest_station %></h5>
            <h5 class="shop-explanation"><span class="font_test">Wifi</span>：<%= shop.wifi %></h5>
          </div>
        </div>
    </div>
  </div>
    <% end %>
    </div>
    <% end %>
  </main>